name: README Animations
on:
  schedule: [{ cron: "0 4 * * *" }]  # diario 04:00 Bogotá
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generar SVGs
        shell: bash
        run: |
          mkdir -p dist

          # 1) Typing banner (con soporte auto claro/oscuro)
          cat > dist/typing-banner.svg <<'SVG'
          <svg xmlns="http://www.w3.org/2000/svg" width="800" height="120" viewBox="0 0 800 120">
            <defs>
              <style>
                .title { font: 700 28px system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; fill: #7c3aed; }
                .role  { font: 500 16px system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; fill: #0ea5e9; }
                @media (prefers-color-scheme: dark) {
                  .title { fill: #a78bfa; }
                  .role  { fill: #67e8f9; }
                }
              </style>
              <clipPath id="cursor-clip">
                <rect x="0" y="0" width="0" height="40">
                  <animate attributeName="width" values="0;780;0" dur="6s" repeatCount="indefinite" keyTimes="0;0.6;1"/>
                </rect>
              </clipPath>
            </defs>

            <g transform="translate(12,42)">
              <text class="title">Santiago Contreras</text>
              <rect x="0" y="-22" width="2" height="34" fill="#22d3ee">
                <animate attributeName="x" values="0;780;0" dur="6s" repeatCount="indefinite" keyTimes="0;0.6;1"/>
                <animate attributeName="opacity" values="1;0;1" dur="0.8s" repeatCount="indefinite"/>
              </rect>
              <g clip-path="url(#cursor-clip)">
                <rect x="0" y="-26" width="780" height="42" fill="transparent"/>
              </g>
            </g>

            <g transform="translate(12,82)" class="role">
              <text>
                <tspan>Java • Spring Boot • MySQL/Postgres • Selenium • SonarQube • React Native • TypeScript • Python • Node.js</tspan>
                <animate attributeName="x" values="0;-820;0" dur="18s" repeatCount="indefinite"/>
              </text>
            </g>
          </svg>
          SVG

          # 2) Orbit rings
          cat > dist/orbit.svg <<'SVG'
          <svg xmlns="http://www.w3.org/2000/svg" width="800" height="180" viewBox="0 0 800 180">
            <defs>
              <style>
                .title { font: 700 18px system-ui,-apple-system,Segoe UI,Roboto,Arial; fill:#475569; }
                @media (prefers-color-scheme: dark) { .title { fill:#e2e8f0; } }
              </style>
              <radialGradient id="grad">
                <stop offset="0" stop-color="#38bdf8" stop-opacity="0.9"/>
                <stop offset="1" stop-color="#8b5cf6" stop-opacity="0.9"/>
              </radialGradient>
            </defs>
            <rect width="800" height="180" fill="transparent"/>
            <g transform="translate(400,90)">
              <circle r="46" fill="url(#grad)"/>
              <circle r="60" fill="none" stroke="#94a3b8" stroke-dasharray="3 6"/>
              <circle r="90" fill="none" stroke="#94a3b8" stroke-dasharray="3 6"/>
              <circle r="120" fill="none" stroke="#94a3b8" stroke-dasharray="3 6"/>
              <g>
                <circle r="6" fill="#22d3ee">
                  <animateTransform attributeName="transform" type="rotate" from="0 0 0" to="360 0 0" dur="8s" repeatCount="indefinite"/>
                  <animate attributeName="cx" values="60;60" dur="8s" repeatCount="indefinite"/>
                </circle>
                <circle r="5" fill="#a78bfa">
                  <animateTransform attributeName="transform" type="rotate" from="180 0 0" to="540 0 0" dur="12s" repeatCount="indefinite"/>
                  <animate attributeName="cx" values="90;90" dur="12s" repeatCount="indefinite"/>
                </circle>
                <circle r="4" fill="#34d399">
                  <animateTransform attributeName="transform" type="rotate" from="90 0 0" to="450 0 0" dur="16s" repeatCount="indefinite"/>
                  <animate attributeName="cx" values="120;120" dur="16s" repeatCount="indefinite"/>
                </circle>
              </g>
            </g>
            <text x="16" y="28" class="title">Tech orbit · Java • Spring Boot • Selenium • React Native • TypeScript • Python</text>
          </svg>
          SVG

          #WAVE DIVIDER (loop continuo, sin salto)
          cat > dist/wave-divider.svg <<'SVG'
          <svg xmlns="http://www.w3.org/2000/svg" width="800" height="80" viewBox="0 0 800 80">
            <defs>
              <!-- colores -->
              <linearGradient id="wave" x1="0" y1="0" x2="1" y2="0">
                <stop offset="0" stop-color="#06b6d4"/>
                <stop offset="1" stop-color="#8b5cf6"/>
              </linearGradient>

              <!-- tile de 200px que se repite -->
              <symbol id="tileA" viewBox="0 0 200 80">
                <path d="M0,40 C50,10 150,70 200,40"
                      fill="none" stroke="url(#wave)" stroke-width="3"
                      stroke-linecap="round" stroke-linejoin="round"
                      vector-effect="non-scaling-stroke"/>
              </symbol>
              <symbol id="tileB" viewBox="0 0 200 80">
                <path d="M0,42 C50,16 150,66 200,42"
                      fill="none" stroke="url(#wave)" stroke-width="2"
                      stroke-linecap="round" stroke-linejoin="round"
                      opacity="0.55" vector-effect="non-scaling-stroke"/>
              </symbol>

              <!-- máscara para desvanecer bordes y evitar flicker en extremos -->
              <linearGradient id="fade" x1="0" y1="0" x2="1" y2="0">
                <stop offset="0" stop-color="#0000"/>
                <stop offset="0.05" stop-color="#000"/>
                <stop offset="0.95" stop-color="#000"/>
                <stop offset="1" stop-color="#0000"/>
              </linearGradient>
              <mask id="edge-fade">
                <rect width="800" height="80" fill="url(#fade)"/>
              </mask>
            </defs>

            <rect width="800" height="80" fill="transparent"/>

            <g mask="url(#edge-fade)">
              <!-- Capa 1 (rápida): repetimos tiles desde -200 a 800 -->
              <g>
                <use href="#tileA" x="-200"/>
                <use href="#tileA" x="0"/>
                <use href="#tileA" x="200"/>
                <use href="#tileA" x="400"/>
                <use href="#tileA" x="600"/>
                <use href="#tileA" x="800"/>
                <animateTransform attributeName="transform" type="translate"
                  from="0 0" to="-200 0" dur="3.2s" repeatCount="indefinite"/>
              </g>

              <!-- Capa 2 (lenta, paralaje) -->
              <g>
                <use href="#tileB" x="-200"/>
                <use href="#tileB" x="0"/>
                <use href="#tileB" x="200"/>
                <use href="#tileB" x="400"/>
                <use href="#tileB" x="600"/>
                <use href="#tileB" x="800"/>
                <animateTransform attributeName="transform" type="translate"
                  from="0 0" to="-200 0" dur="6.4s" repeatCount="indefinite"/>
              </g>
            </g>
          </svg>
          SVG

      - name: Publicar a rama output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
