name: Snake

on:
  schedule: [{ cron: "0 3 * * *" }]  # diario 03:00 Bogotá
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generar snake (modo claro y oscuro)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: chillkavo
          outputs: |
            dist/snake-light.svg?palette=github-light&background=#ffffff
            dist/snake-dark.svg?palette=github-dark&background=#0d1117

      - name: Publicar a rama output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

